#Stasis Rod config

#==================== modes =====================

#insted of spawning a armor stand when you use the fishing rod the armor stand spawns on command and stays there till u pull the fishing rod
#the armor stand is small and invisible
#if you had a fishing rod but you lost it and you want to get rid of the armorstand just bind another fishing rod
#if you set it to false it will spawn a armor stand when you use the fishing rod
# ↳it may give you a litlle LITLLE bit of performance but it's really up to you
alaways-armorstanmd: true


#just deletes the custom data of the fishing rod after use.
one-use: true

#instead of saving with a command you can now save by fishing on to you're pressure plate and sneaking
#note: once you have already fished and the hook is on presssure plate then you can sneak!
save-fishing: true


#checks if you saved on pressure plate!
check-if-pressureplate: true


#ONLY if alaways-armorstanmd is true
#Saves the coordinats the vanilla way which means when you enter the nether portal with the hook on pressureplate
vanilla-saving: true


#==================== durablitie =====================


#this functions makes it so if it's true the stasis rod will have 4 durabilitie and once it is used it will destroy the rod

destroy-rod: false



#==================== meta =====================


#set "" to not rename it
#changes the name of the rod once it saved
rod-name: "stasis rod"

#player can set custom name
custom-name: true


#show cord in lore on the fishing rod
show-cords: false

#==================== looks =====================

#adds a enchantment glint to a fishing rod when saved
#keep in mind that it will stay with this glint for the whole time
enchantment-glint: false




#==================== chunks =====================

#how many of chunks it should load when you use the fishing rod
chunks: 4


#for how many seconds it should load the chunks
chunks-sec: 4


#==================== messages =====================

saving-sRod: "<grey>stasisRod</grey><dark_grey>:</dark_grey> You saved location to you're fishing rod"
not-holding-fishing-rods: "<grey>stasisRod</grey><dark_grey>:</dark_grey> You are not holding any fishing rods"


