name: UptownsStasisRod
description: Adds stasis rods to minecraft! use /stasisRod on a fishing rod to bind cords to fishing rods
version: '${version}'

main: me.piksel.uptownsStasisRod.UptownsStasisRod
api-version: '1.21'
load: STARTUP

authors: [ PikselWasTaken ]
website: https://modrinth.com/plugin/uptowns-stasis-rod
permissions:
  uptown.stasisRod.use:
    default: true
commands:
  stasisRod:
    usage: "/stasisRod"
    aliases: [sRod,sr,rod]
